export interface PdfSection {
  heading: string;
  html: string;
}

function slug(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'aagam-report';
}

export function exportReportPdf(title: string, subtitle: string, sections: PdfSection[]) {
  const body = sections
    .map(
      (s) => `
      <section>
        <h2>${escapeHtml(s.heading)}</h2>
        <div class="section-body">${s.html}</div>
      </section>`
    )
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: #111;
      padding: 48px 56px;
      line-height: 1.55;
      font-size: 15px;
    }
    h1 { font-size: 26px; margin: 0 0 8px; }
    .sub { color: #555; margin-bottom: 28px; font-size: 15px; }
    h2 {
      font-size: 17px;
      margin: 28px 0 10px;
      padding-bottom: 6px;
      border-bottom: 1px solid #ddd;
    }
    p { margin: 0 0 10px; }
    ul, ol { margin: 0 0 12px; padding-left: 18px; }
    li { margin-bottom: 4px; }
    .meta { color: #666; font-size: 12px; margin-top: 4px; }
    .card { border: 1px solid #e5e5e5; border-radius: 8px; padding: 12px 14px; margin-bottom: 10px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="sub">${escapeHtml(subtitle)}</div>
  ${body}
  <p class="meta">Generated by AAGAM · ${new Date().toLocaleString()}</p>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const iframe = document.createElement('iframe');
  iframe.setAttribute(
    'style',
    'position:fixed;right:0;bottom:0;width:1px;height:1px;border:0;opacity:0;pointer-events:none'
  );
  iframe.srcdoc = html;
  document.body.appendChild(iframe);

  let printed = false;
  const printFrame = () => {
    if (printed) return;
    printed = true;
    try {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    } catch {
      const a = document.createElement('a');
      a.href = url;
      a.download = `${slug(title)}.html`;
      a.click();
    }
    setTimeout(() => {
      iframe.remove();
      URL.revokeObjectURL(url);
    }, 4000);
  };

  iframe.onload = () => setTimeout(printFrame, 250);
  setTimeout(printFrame, 800);
}

export function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
