// ============================================================
// Adversarial Critic — Agent Resource Exchange
// ============================================================
// Stress-tests specialist findings, identifies unsupported leaps,
// detects omitted requirements, and produces a structured defect report.
// ============================================================

import { v4 as uuidv4 } from 'uuid';
import { eventBus } from '@/lib/events/event-emitter';
import { withTrace } from '@/lib/observability/neatlogs';
import { ProviderGateway } from '@/lib/providers/gateway';
import type { Claim, EvidenceItem, DefectItem } from '@/lib/types/claims';

export interface CriticResult {
  defects: DefectItem[];
  missingRequirements: string[];
  weakAssumptions: string[];
  criticSummary: string;
}

export async function runAdversarialCritic(
  taskGoal: string,
  claims: Claim[],
  evidenceItems: EvidenceItem[],
  gateway: ProviderGateway,
  runId: string
): Promise<CriticResult> {
  return withTrace(
    {
      name: 'adversarial-critic',
      kind: 'CHAIN',
      sessionId: runId,
      attributes: {
        run_id: runId,
        claim_count: claims.length,
        evidence_count: evidenceItems.length,
      },
    },
    async () => {
      eventBus.log(runId, 'info', 'Adversarial Critic: Stress-testing claims and probing for gaps/flaws...');

      const systemPrompt = `You are a ruthless, skeptical adversarial reviewer and senior risk auditor.
Your job is to actively attempt to BREAK and challenge the claims and recommendations produced by the agents.

Scrutinize:
1. What critical claims lack verifiable evidence?
2. What explicit requirement from the user task is missing or shallow?
3. Are numerical figures (market size, revenue projections, CAC/LTV) mathematically feasible?
4. Are named competitors actually comparable, or are key incumbents omitted?
5. Is the conclusion overconfident or ignoring regulatory/market tailwinds?

Return JSON:
{
  "defects": [
    {
      "severity": "CRITICAL" | "MAJOR" | "MINOR",
      "dimension": "evidence" | "completeness" | "numericalConsistency" | "riskAnalysis" | "competitorAnalysis",
      "description": "Specific flaw detected",
      "affectedClaimIds": ["id1"],
      "recommendedAction": "Actionable instruction to resolve defect",
      "targetSpecialistRole": "Quantitative Analyst" | "Market Researcher" | "Evidence Verifier" | "Risk Analyst",
      "expectedQualityGain": 0.15,
      "estimatedResourceCost": 0.04
    }
  ],
  "missingRequirements": ["..."],
  "weakAssumptions": ["..."],
  "criticSummary": "Concise summary of weaknesses"
}`;

      const userPrompt = `## Task Goal & Requirements
${taskGoal}

## Claims Generated by Specialists
${JSON.stringify(claims.map(c => ({
  id: c.id,
  claim: c.claim,
  importance: c.importance,
  status: c.verificationStatus,
  evidence: c.evidence,
  confidence: c.confidence,
})), null, 2)}

## Evidence Available
${JSON.stringify(evidenceItems.slice(0, 15).map(e => ({
  agent: e.sourceAgent,
  content: e.content,
  dataPoints: e.dataPoints,
})), null, 2)}

Produce a rigorous adversarial critique and defect list. Return JSON:`;

      try {
        const availableModels = gateway.getAvailableModels();
        const modelToUse = availableModels.includes('gpt-5-nano') ? 'gpt-5-nano' : (availableModels[0] || 'gpt-5-nano');

        const response = await gateway.generate(modelToUse, userPrompt, {
          systemPrompt,
          temperature: 0.25,
          maxTokens: 2000,
          responseFormat: 'json',
        });

        const parsed = JSON.parse(response.content);
        const defects: DefectItem[] = [];

        if (Array.isArray(parsed.defects)) {
          for (const d of parsed.defects) {
            defects.push({
              id: uuidv4(),
              severity: d.severity === 'CRITICAL' ? 'CRITICAL' : d.severity === 'MAJOR' ? 'MAJOR' : 'MINOR',
              dimension: String(d.dimension || 'reasoning'),
              description: String(d.description || ''),
              affectedClaimIds: Array.isArray(d.affectedClaimIds) ? d.affectedClaimIds : [],
              recommendedAction: String(d.recommendedAction || ''),
              targetSpecialistRole: String(d.targetSpecialistRole || 'Evidence Verifier'),
              expectedQualityGain: typeof d.expectedQualityGain === 'number' ? Math.min(0.3, Math.max(0.05, d.expectedQualityGain)) : 0.1,
              estimatedResourceCost: typeof d.estimatedResourceCost === 'number' ? Math.min(0.1, Math.max(0.01, d.estimatedResourceCost)) : 0.03,
            });
          }
        }

        const missingRequirements = Array.isArray(parsed.missingRequirements) ? parsed.missingRequirements : [];
        const weakAssumptions = Array.isArray(parsed.weakAssumptions) ? parsed.weakAssumptions : [];
        const criticSummary = String(parsed.criticSummary || 'Critique complete.');

        eventBus.emit({
          id: uuidv4(),
          runId,
          type: 'critic.completed',
          timestamp: Date.now(),
          payload: {
            defectCount: defects.length,
            criticalDefects: defects.filter(d => d.severity === 'CRITICAL').length,
            missingRequirements,
            criticSummary,
          },
        });

        eventBus.log(
          runId,
          defects.length === 0 ? 'info' : 'warn',
          `Adversarial Critic: Identified ${defects.length} defects (${defects.filter(d => d.severity === 'CRITICAL').length} critical). Summary: ${criticSummary}`
        );

        return {
          defects,
          missingRequirements,
          weakAssumptions,
          criticSummary,
        };

      } catch (err) {
        eventBus.log(runId, 'warn', `Critic fallback engaged: ${err instanceof Error ? err.message : String(err)}`);

        // Heuristic fallback defect generation
        const unverified = claims.filter(c => c.verificationStatus !== 'VERIFIED');
        const defects: DefectItem[] = unverified.map(c => ({
          id: uuidv4(),
          severity: c.importance === 'CRITICAL' ? 'CRITICAL' : 'MAJOR',
          dimension: 'evidence',
          description: `Claim lacks confirmed empirical backing: "${c.claim.substring(0, 80)}..."`,
          affectedClaimIds: [c.id],
          recommendedAction: `Provide primary benchmark or quantitative source for claim.`,
          targetSpecialistRole: 'Evidence Verifier',
          expectedQualityGain: 0.12,
          estimatedResourceCost: 0.03,
        }));

        return {
          defects,
          missingRequirements: [],
          weakAssumptions: ['Assumes linear customer adoption under baseline pricing'],
          criticSummary: `Flagged ${defects.length} unverified claims requiring targeted empirical audit.`,
        };
      }
    }
  );
}
