export const AAGAM_FEATURES = [
  { id: 'f01', name: 'Write the problem in English' },
  { id: 'f02', name: 'Pull out the real objective' },
  { id: 'f03', name: 'Guess the industry' },
  { id: 'f04', name: 'Guess the geography' },
  { id: 'f05', name: 'Separate must-haves from defaults' },
  { id: 'f06', name: 'Design the team, not you' },
  { id: 'f07', name: 'Assign specialist roles' },
  { id: 'f08', name: 'Buy a tool only if it pays' },
  { id: 'f09', name: 'Pick the right model' },
  { id: 'f10', name: 'Fallback if a provider fails' },
  { id: 'f11', name: 'Ask for budget before work' },
  { id: 'f12', name: 'Hold money so it is not spent twice' },
  { id: 'f13', name: 'Approve, cut, or reject spend' },
  { id: 'f14', name: 'Track what was actually used' },
  { id: 'f15', name: 'Return unused budget' },
  { id: 'f16', name: 'Per-run wallets' },
  { id: 'f17', name: 'Pay per run, not seats' },
  { id: 'f18', name: 'Run independent work in parallel' },
  { id: 'f19', name: 'Rewire the plan when a step fails' },
  { id: 'f20', name: 'Research agents execute for real' },
  { id: 'f21', name: 'Coding happens in an isolated folder' },
  { id: 'f22', name: 'Pick Codex, Cursor, or Kiro' },
  { id: 'f23', name: 'Tie AO sessions back to this run' },
  { id: 'f24', name: 'Live AO status — never faked' },
  { id: 'f25', name: 'Keep a lineage for code artifacts' },
  { id: 'f26', name: 'Task, architecture, and agent sessions' },
  { id: 'f27', name: 'Only pass verified work downstream' },
  { id: 'f28', name: 'Extract claims from the answer' },
  { id: 'f29', name: 'Check citations' },
  { id: 'f30', name: 'Flag contradictions' },
  { id: 'f31', name: 'Attack the answer on purpose' },
  { id: 'f32', name: 'Score quality on 8 dimensions' },
  { id: 'f33', name: 'How much of the answer is evidenced' },
  { id: 'f34', name: 'Who actually added value' },
  { id: 'f35', name: 'Drop agents that did almost nothing' },
  { id: 'f36', name: 'Change the team only if it is worth it' },
  { id: 'f37', name: 'Keep V1 if V2 would be worse' },
  { id: 'f38', name: 'Live V1 → V2 evolution' },
  { id: 'f39', name: 'Swap a model if quality is weak' },
  { id: 'f40', name: 'Swap tools if quality is weak' },
  { id: 'f41', name: 'Neatlogs watches. AAGAM decides.' },
  { id: 'f42', name: 'Capability marketplace' },
  { id: 'f43', name: 'Web, news, and paper search' },
  { id: 'f44', name: 'Finance and risk tools' },
  { id: 'f45', name: 'Market size modeling' },
  { id: 'f46', name: 'Regulatory research' },
  { id: 'f47', name: 'History as decision memos' },
  { id: 'f48', name: 'Export PDF' },
  { id: 'f49', name: '110-task proof catalog' },
  { id: 'f50', name: 'Reliability across repeats' },
] as const;
